### ISSUE TITLE
Post calls are being answered 200 but not actually hitting my server.

### ISSUE THREAD

**Issue by cameragadget** [cameragadget/t_standup_app#3]
User Story:
AAU I want to be able to create a new standup group from the dashboard

The Error:
Upon submission of my createTeam function (team.dataservice.js line 22) I receive a 200 http response in the console, but not a returned object.
Terminal states: 
POST /api/teams 200 17.273 ms - 3105

nothing is persisting and the database is not even showing up in my mongoHub.

Attempts to fix:
Have tried .stringify to see if not in JSON.  Have rebuilt entire api routing to no avail. Have changed method calls to mongoose calls rather then custom calls.

Help me Obi Wan Kenobi.  You're my only hope.....

**Comment by h4w5** [comment]
Assigning myself.

**Comment by h4w5** [comment]
@cameragadget is this happening on the currently pushed master commit? Can you link to the relevant route, controller and model in here?

**Comment by cameragadget** [comment]
this is happening on the currently pushed master, yes. here are links to code:

https://github.com/cameragadget/t_standup_app/blob/master/routes/api_routes.js
https://github.com/cameragadget/t_standup_app/blob/master/controllers/api.js
https://github.com/cameragadget/t_standup_app/blob/master/models/team.js
call originates at line 22 of dataservice:
https://github.com/cameragadget/t_standup_app/blob/master/public/js/app/services/team.dataservice.js

**Comment by cameragadget** [comment]
Thanks for looking into this for me.  Casper and I tried to figure this out for two hours and are stumped.

**Comment by h4w5** [comment]
Ah, also, in the future once I'm assigned you should Slack me your .env stuff.

**Comment by h4w5** [comment]
So: you are [loading your API routes at `/api`](https://github.com/cameragadget/t_standup_app/blob/master/server.js#L46), and then [defining it as a `POST /api/teams`](https://github.com/cameragadget/t_standup_app/blob/master/routes/api_routes.js#L9), which means your route is:

```
POST /api/api/teams
```

You're also [using `app.use` for your root route instead of `app.get`](https://github.com/cameragadget/t_standup_app/blob/master/routes/api_routes.js#L9), which means that anything that is not being caught by your API handler is returning your rendered home page HTML (`app.use` means any method, any url that begins with). That's why your request is not a 404. Your request has been returning your homepage, which is easily seen in Postman.

**Comment by cameragadget** [comment]
Thanks for the help! still learning the process, if I have any more issues I'll be sure to follow the protocol.
